#! /bin/bash

printf "Changing to home directory\n"
cd
printf "\nDownloading from cExplr the repository names gitScripts\n\n"
echo git clone https://github.com/cExplr/gitScripts.git
git clone https://github.com/cExplr/gitScripts.git
printf "\nEntering the folder gitScripts\n"
cd gitScripts
printf "\n Copying gitClone and placing into parent folder"
cp gitClone ..
cd ..
printf "\nChanging permission to executable\n"
chmod +x gitClone
printf "\n Please edit if needed the directory, remote and branch"
nano gitClone
printf "Confirm with the editing? (y/n): \n"
read  editOpt
while ! [ $editOpt == "y" ]
do
nano  gitClone
done
printf "\nInstallation completed!\n\n"
