#! /bin/bash

printf "Changing to home directory\n"
cd
printf "\nDownloading from cExplr the repository names gitScripts\n\n"
echo git clone https://github.com/cExplr/gitScripts.git
git clone https://github.com/cExplr/gitScripts.git
printf "\nEntering the folder gitScripts\n"
cd gitScripts
printf "\n Copying quickpush and placing into parent folder"
cp quickPush ..
cd ..
printf "\nChanging permission to executable\n"
chmod +x quickPush
printf "\n Please edit if needed the directory, remote and branch"
nano quickPush
read -p "Enter a shorter name of the repository for naming : "
printf "[*] Renaming quickPush to push$REPLY"
mv quickPush push$REPLY
echo "Done"
printf "\n\nInstallation completed!\n\nTYPE cd COMMAND TO VIEW THE INSTALLED FILES\n\n"
