#! /bin/bash

printf "Changing to home directory\n"
cd
printf "\nDownloading from cExplr the repository names gitScripts\n\n"
echo git clone https://github.com/cExplr/gitScripts.git
git clone https://github.com/cExplr/gitScripts.git
printf "\nEntering the folder gitScripts\n"
cd gitScripts
printf "\n Copying quickpull and placing into parent folder"
cp quickPull ..
cd ..
printf "\nChanging permission to executable\n"
chmod +x quickPull
printf "\n Please edit if needed the directory, remote and branch"
nano quickPull
read -p "Enter a shorter version of the target repository for naming: "
printf "\n[*] Renaming quickPull to pull$REPLY"
mv quickPull pull$REPLY
echo "Done"
printf "\n\nInstallation completed!\n\nTYPE cd COMMAND TO VIEW THE INSTALLED FILES\n\n"
